[package]
name = "maml"
version = "0.0.0"
edition = "2024"
description = "MAML - Minimal Abstract Markup Language"
repository = "https://github.com/maml-dev/maml-rs"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
ariadne = "0.6.0"
chumsky = "1.0.0-alpha.7"
